# Generated by Django 2.1.4 on 2019-03-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20190302_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='DueDate',
            field=models.DateField(help_text='YY-MM-DD'),
        ),
    ]
