# Generated by Django 2.1.4 on 2019-03-06 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_tasks_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='DueDate',
            field=models.DateField(help_text='YYYY-MM-DD'),
        ),
    ]
